name: CI Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'  
        java-package: jdk
        architecture: x64
        check-latest: false

    - name: Build and Test with Maven
      run: mvn clean verify --no-transfer-progress --batch-mode

    - name: Upload JaCoCo coverage report
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # Add Codecov token to GitHub Secrets if using Codecov for coverage reports.
